### PR TITLE
Refactor - Awesome Books Classes

### PR DESCRIPTION
**Pull request by Aduda-Boaz**
This PR is for learning purposes on how to use JavaScript classes instead of objects and arrays.
The product is built by @JuliCarracedo and @Aduda-Boaz. Together we have done as per the instruction to refactor the JS objects and arrays into classes. And we are happy to present our project for review.

### CODE REVIEW

**Comment by Aduda-Boaz** [comment]
Screenshot from 2021-08-11 00-02-21
The linters have failed to work but on the local version, it works fine and shows no errors as in the screenshot. The linters does not run automatically on the GitHub flow despit having the setup correct.

**Comment by bellom** [comment]
@Aduda-Boaz @JuliCarracedo 

Kindly use the correct linter config file, [checkout JS config file](https://github.com/microverseinc/linters-config/blob/master/javascript/.github/workflows/linters.yml)

**Comment by bellom** [comment]
@Aduda-Boaz @JuliCarracedo 

Kindly use the correct linter config file, [checkout JS config file](https://github.com/microverseinc/linters-config/blob/master/javascript/.github/workflows/linters.yml)

**Comment by Davidosky007** [comment]
## Hi @Aduda-Boaz @JuliCarracedo 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Pull request merged**
